/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author felip
 */
public class JogoDeAdivinhacao extends javax.swing.JFrame {

    /**
     * Creates new form JogoDeAdivinhacao
     */
    public JogoDeAdivinhacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGenio = new javax.swing.JLabel();
        lblPensamento = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        girNumero = new javax.swing.JSpinner();
        btnPensamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo de advinhação");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Genio1-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        lblPensamento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPensamento.setForeground(new java.awt.Color(0, 0, 255));
        lblPensamento.setText("<html>Estou pensando em um numero entre 0 e 5, tente adivinhar</html>");
        getContentPane().add(lblPensamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 190, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/balao2-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        girNumero.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)5), Byte.valueOf((byte)1)));
        girNumero.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 0, 0), new java.awt.Color(255, 51, 51)));
        getContentPane().add(girNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 50, 30));

        btnPensamento.setBackground(new java.awt.Color(255, 255, 0));
        btnPensamento.setText("Palpite");
        btnPensamento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(255, 51, 51), new java.awt.Color(204, 0, 0), new java.awt.Color(204, 0, 0)));
        btnPensamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPensamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnPensamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 100, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPensamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPensamentoActionPerformed
        // TODO add your handling code here:
        byte numero = (byte) girNumero.getValue();
        byte computador = (byte) (0 + Math.random()*(6-0));
        
        if(numero == computador){
            lblPensamento.setText("Você acertou !!");
        }
        else{
            lblPensamento.setText(String.format("Você errou!! Pensei em %d", computador));
        }
    }//GEN-LAST:event_btnPensamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDeAdivinhacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDeAdivinhacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPensamento;
    private javax.swing.JSpinner girNumero;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblPensamento;
    // End of variables declaration//GEN-END:variables
}
